language: python

cache: pip

dist: trusty

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
    - TOX_ENV=python27-django18
    - TOX_ENV=python27-django111
    - TOX_ENV=python34-django18
    - TOX_ENV=python34-django111
    - TOX_ENV=python34-django20
    - TOX_ENV=python35-django18
    - TOX_ENV=python35-django111
    - TOX_ENV=python35-django20
    - TOX_ENV=python36-django18
    - TOX_ENV=python36-django111
    - TOX_ENV=python36-django20
    - TOX_ENV=flake8
    - TOX_ENV=isort

install: pip install codecov tox-travis

script: tox -e $TOX_ENV

after_success: codecov -e $TOX_ENV
