language: python

cache: pip

dist: trusty

sudo: false

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=python27-django18
    - python: "2.7"
      env: TOXENV=python27-django111
    - python: "3.4"
      env: TOXENV=python34-django18
    - python: "3.4"
      env: TOXENV=python34-django111
    - python: "3.4"
      env: TOXENV=python34-django20
    - python: "3.5"
      env: TOXENV=python35-django18
    - python: "3.5"
      env: TOXENV=python35-django111
    - python: "3.5"
      env: TOXENV=python35-django20
    - python: "3.6"
      env: TOXENV=python36-django18
    - python: "3.6"
      env: TOXENV=python36-django111
    - python: "3.6"
      env: TOXENV=python36-django20
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=isort

install: pip install codecov tox-travis

script: tox

after_success: codecov
